"""add crm lead campaign tables

Revision ID: 61720afe23a5
Revises: 50bd6af3a5d5
Create Date: 2026-08-28 15:49:37.711581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61720afe23a5'
down_revision: Union[str, Sequence[str], None] = '50bd6af3a5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'STOPPED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('calling_start_time', sa.Time(), nullable=True),
    sa.Column('calling_end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUEUED', 'CALLING', 'CONNECTED', 'QUALIFIED', 'INTERESTED', 'NOT_INTERESTED', 'CALLBACK', 'APPOINTMENT_BOOKED', 'DO_NOT_CALL', 'FAILED', 'COMPLETED', name='leadstatus'), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('last_called_at', sa.DateTime(), nullable=True),
    sa.Column('next_call_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_leads_campaign_id'), 'campaign_leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_leads_lead_id'), 'campaign_leads', ['lead_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='followupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_lead_id'), 'followups', ['lead_id'], unique=False)
    op.create_index(op.f('ix_followups_scheduled_at'), 'followups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_followups_status'), 'followups', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followups_status'), table_name='followups')
    op.drop_index(op.f('ix_followups_scheduled_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_lead_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_campaign_leads_lead_id'), table_name='campaign_leads')
    op.drop_index(op.f('ix_campaign_leads_campaign_id'), table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
