from enum import Enum


class LeadStatus(str, Enum):
    NEW = "NEW"
    QUEUED = "QUEUED"
    CALLING = "CALLING"
    CONNECTED = "CONNECTED"
    QUALIFIED = "QUALIFIED"
    INTERESTED = "INTERESTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    CALLBACK = "CALLBACK"
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    DO_NOT_CALL = "DO_NOT_CALL"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class CampaignStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"
    COMPLETED = "COMPLETED"


class FollowupStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class CallStatus(str, Enum):
    QUEUED = "QUEUED"
    INITIATED = "INITIATED"
    RINGING = "RINGING"
    ANSWERED = "ANSWERED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    NO_ANSWER = "NO_ANSWER"
    BUSY = "BUSY"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class CallOutcome(str, Enum):
    INTERESTED = "INTERESTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    CALLBACK = "CALLBACK"
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    DO_NOT_CALL = "DO_NOT_CALL"
    WRONG_NUMBER = "WRONG_NUMBER"
    NO_RESPONSE = "NO_RESPONSE"


class QualificationStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    UNQUALIFIED = "UNQUALIFIED"
    QUALIFIED = "QUALIFIED"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"
